# db.yml
#   PostgreSQL setup
#
# This software is public domain.
#

- name: Database Server Setup
  hosts: db
  sudo: yes
  tasks:
    - name: Install Postgresql
      tags:
        - update-packages
        - update-postgres
      apt: name=postgresql-9.3

    - name: Install python libraries required to manage postgresql with Ansible
      tags:
        - update-packages
        - update-postgres
      apt: name=python-psycopg2

    - name: Create Canvas DB user
      tags:
        - update-dbs
        - update-postgres
      postgresql_user: name={{ canvas_db_user }} password={{ canvas_db_password }}
      sudo_user: postgres

    - name: Create Canvas databases
      tags:
        - update-dbs
        - update-postgres
      postgresql_db: name={{ item }} owner={{ canvas_db_user }}
      sudo_user: postgres
      with_items: canvas_db_names

    - name: Listen on all addresses
      tags:
        - update-postgres
      lineinfile: dest={{ postgres_conf }} line="listen_addresses = '*'" regexp=^listen_addresses
      register: postgres_conf_edit

    - name: Allow canvas user to connect remotely
      tags:
        - update-postgres
      lineinfile: dest={{ postgres_hba_conf }} insertbefore="^# DO NOT DISABLE!$" line="host {{ item }} canvas 192.168.100.0/24 md5"
      with_items: canvas_db_names
      register: postgres_hba_edit

    - name: Restart postgresql
      tags:
        - update-postgres
      service: name=postgresql state=restarted
      when: postgres_conf_edit|changed or postgres_hba_edit|changed
